---
kind: pipeline
type: kubernetes
name: Test

platform:
    os: linux
    arch: arm

steps:
  - name: backend
    image: python:3.9-slim
    environment:
      CRYPTOGRAPHY_DONT_BUILD_RUST: 1
    commands:
      - apt-get update
      - mkdir -p /usr/share/man/man1/
      - touch /usr/share/man/man1/rmid.1.gz.dpkg-tmp
      - echo "[global]\nextra-index-url=https://www.piwheels.org/simple" >> /etc/pip.conf
      - pip install --upgrade pip
      - apt-get install -y pdftk build-essential python3-dev libssl-dev libffi-dev cargo
      - pip install --prefer-binary -r requirements.txt
      - python app/tests/run_tests.py
    resources:
      requests:
        cpu: 1000
        memory: 750MiB

  - name: frontend
    image: node:8.16-alpine
    commands:
      - apk add build-base python
      - cd ui
      - npm install
      - npm run test
    resources:
      requests:
        cpu: 1000
        memory: 750MiB

---
kind: pipeline
type: kubernetes
name: Image Staging

platform:
    os: linux
    arch: arm

depends_on:
  - Test

steps:
  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: dnd-machine
      build_args: GIT_BRANCH=${DRONE_BRANCH},GIT_COMMIT=${DRONE_COMMIT},GIT_TAG=unstable
      tags: ${DRONE_BRANCH},unstable
      insecure_registry: true
    resources:
      requests:
        cpu: 2000
        memory: 750MiB

---
kind: pipeline
type: kubernetes
name: Image Production

platform:
    os: linux
    arch: arm

trigger:
  event:
  - tag

depends_on:
  - Image Staging

steps:
  - name: build
    image: docker-registry.pikube.dev:31443/drone-genuinetools-img
    settings:
      registry: docker-registry-service.docker-registry:5000
      repo: dnd-machine
      build_args: GIT_BRANCH=${DRONE_BRANCH},GIT_COMMIT=${DRONE_COMMIT},GIT_TAG=${DRONE_TAG}
      auto_tag: true
      insecure_registry: true
    resources:
      requests:
        cpu: 2000
        memory: 750MiB

---
kind: signature
hmac: dbc5a85619e8ed65454d54ec8e0404c721fdbd0f37db28710d1767b25226afc6

...
