---
kind: pipeline
name: test

platform:
    os: linux
    arch: arm

steps:
  - name: backend2
    image: python:2-alpine
    commands:
      - apk add build-base openssl-dev libffi-dev
      - pip install -r requirements.txt
      - python app/tests/run_tests.py

  - name: backend3
    image: python:3-alpine
    commands:
      - apk add build-base openssl-dev libffi-dev
      - pip install -r requirements.txt
      - python app/tests/run_tests.py

  - name: frontend
    image: node:8.15-alpine
    volumes:
      - name: cache
        path: /drone/src/ui/node_modules
    commands:
      - apk add build-base
      - cd ui
      - npm install
      - npm run test

volumes:
  - name: cache
    host:
      path: /var/cache/drone/node_modules

---
kind: pipeline
name: dockerize

platform:
    os: linux
    arch: arm

trigger:
  event:
  - push
  status:
  - success

depends_on:
  - test

steps:
  - name: docker
    image: docker
    commands:
        - docker build -t dnd-machine:staging .
    volumes:
      - name: socket
        path: /var/run/docker.sock

  - name: restart
    image: appleboy/drone-ssh:linux-arm
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      script:
        - >
          docker restart dndmachine_staging || docker run \
            --detach \
            --publish 5005:5000/tcp \
            --mount "type=bind,src=/etc/dnd-machine/staging.json\,dst=/dnd-machine/app/config.local.json" \
            --restart on-failure:3 \
            --name dndmachine_staging \
            dnd-machine:staging

volumes:
- name: socket
  host:
    path: /var/run/docker.sock

---
kind: pipeline
name: stage

platform:
    os: linux
    arch: arm

trigger:
  event:
  - push
  status:
  - success

depends_on:
  - test

steps:
  - name: package
    image: node:8.15-alpine
    volumes:
      - name: cache
        path: /drone/src/ui/node_modules
    commands:
      - apk add build-base
      - ( cd ui && npm install && npm run build:production )
      - |
        tar \
            --exclude app/Dockerfile \
            --exclude app/docker \
            --exclude app/tests \
            -zcvf \
                "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz" \
                *.md \
                *.txt \
                run.py \
                app/

  - name: copy
    image: appleboy/drone-scp:linux-arm
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      target: ~/code/staging
      source: "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz"

  - name: deploy
    image: appleboy/drone-ssh:linux-arm
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      script:
        - cd ~/code/staging
        - mkdir -p "${DRONE_COMMIT_SHA:0:8}"
        - |
          tar \
              --directory "${DRONE_COMMIT_SHA:0:8}" \
              -zxvf "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz"
        - cp latest/app/config.local.json "${DRONE_COMMIT_SHA:0:8}/app/"
        - . ~/.python-env/dnd-machine-beta/bin/activate
        - pip install -r "${DRONE_COMMIT_SHA:0:8}/requirements.txt"
        - rm latest
        - ln -s "${DRONE_COMMIT_SHA:0:8}" latest
        - sudo systemctl restart dndmachine-beta

volumes:
  - name: cache
    host:
      path: /var/cache/drone/node_modules

---
kind: pipeline
name: deploy

platform:
    os: linux
    arch: arm

trigger:
  branch:
  - master
  event:
  - push
  status:
  - success

depends_on:
  - stage

steps:
  - name: package
    image: node:8.15-alpine
    volumes:
      - name: cache
        path: /drone/src/ui/node_modules
    commands:
      - apk add build-base
      - ( cd ui && npm install && npm run build:production )
      - |
        tar \
            --exclude app/Dockerfile \
            --exclude app/docker \
            --exclude app/tests \
            -zcvf \
                "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz" \
                *.md \
                *.txt \
                run.py \
                app/

  - name: copy
    image: appleboy/drone-scp:linux-arm
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      target: ~/code/production
      source: "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz"

  - name: deploy
    image: appleboy/drone-ssh:linux-arm
    settings:
      host:
        from_secret: ssh_host
      username:
        from_secret: ssh_user
      key:
        from_secret: ssh_key
      script:
        - cd ~/code/production
        - mkdir -p "${DRONE_COMMIT_SHA:0:8}"
        - |
          tar \
              --directory "${DRONE_COMMIT_SHA:0:8}" \
              -zxvf "dnd-machine.${DRONE_COMMIT_SHA:0:8}.tar.gz"
        - cp latest/app/config.local.json "${DRONE_COMMIT_SHA:0:8}/app/"
        - . ~/.python-env/dnd-machine/bin/activate
        - pip install -r "${DRONE_COMMIT_SHA:0:8}/requirements.txt"
        - rm latest
        - ln -s "${DRONE_COMMIT_SHA:0:8}" latest
        - sudo systemctl restart dndmachine

volumes:
  - name: cache
    host:
      path: /var/cache/drone/node_modules

---
kind: signature
hmac: 3cffccf6fa79d3c9cbe18fe0956d39cf30c46bd16597edd8ad1c22b795bd462a

...
