version: '2'

services:
    nginx:
        build:
            context: .
            dockerfile: nginx/Dockerfile
        container_name: dnd-nginx
        ports:
            - 8080:80
        networks:
            dnd-network:
                aliases:
                    - proxy
        volumes:
            - .:/dnd-machine
        depends_on:
          - flask
          - node

    flask:
        build:
            context: .
            dockerfile: app/Dockerfile
        container_name: dnd-flask
        networks:
            dnd-network:
                aliases:
                    - api
        user: "${UID}:${GID}"
        volumes:
            - .:/dnd-machine

    node:
        build:
            context: ui
            dockerfile: Dockerfile
        container_name: dnd-node
        networks:
            dnd-network:
                aliases:
                    - ui
        user: "${UID}:${GID}"
        volumes:
            - ./ui/docker:/dnd-machine/ui/docker
            - ./ui/.babelrc:/dnd-machine/ui/.babelrc
            - ./ui/.eslintrc:/dnd-machine/ui/.eslintrc
            - ./ui/package.json:/dnd-machine/ui/package.json
            - ./ui/package-lock.json:/dnd-machine/ui/package-lock.json
            - ./ui/src:/dnd-machine/ui/src
            - ./ui/tests:/dnd-machine/ui/tests
            - ./ui/coverage:/dnd-machine/ui/coverage
            - ./ui/webpack.config.js:/dnd-machine/ui/webpack.config.js

networks:
    dnd-network:
        driver: bridge
